### ISSUE TITLE
Support DNS traffic switching using Alias records

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-aws-agent#36]
We need to support Alias records for DNS traffic switching, i.e. we need to adapt the following code part to not only support CNAME records:
https://github.com/zalando-zmon/zmon-aws-agent/blob/master/zmon_aws_agent/aws.py#L53

Background: Senza switches from CNAME to Alias records (https://github.com/zalando-stups/senza/issues/197).

**Comment by hjacobs** [comment]
NOTE: We should support both CNAME and Alias records.

**Comment by hjacobs** [comment]
```
15:21:08.567 zmon-zmon /var/log/application.log  Aug  2 13:21:05 ip-172-31-142-36 docker/4be9b9f37b2f[943]: Traceback (most recent call last):  
15:21:08.567 zmon-zmon /var/log/application.log  Aug  2 13:21:05 ip-172-31-142-36 docker/4be9b9f37b2f[943]:   File "/usr/local/bin/zmon-aws-agent", line 9, in <module>  
15:21:08.567 zmon-zmon /var/log/application.log  Aug  2 13:21:05 ip-172-31-142-36 docker/4be9b9f37b2f[943]:     load_entry_point('zmon-aws-agent==0.2', 'console_scripts', 'zmon-aws-agent')()  
15:21:08.567 zmon-zmon /var/log/application.log  Aug  2 13:21:05 ip-172-31-142-36 docker/4be9b9f37b2f[943]:   File "/usr/local/lib/python3.5/dist-packages/zmon_aws_agent-0.2-py3.5.egg/zmon_aws_agent/main.py", line 110, in main  
15:21:08.567 zmon-zmon /var/log/application.log  Aug  2 13:21:05 ip-172-31-142-36 docker/4be9b9f37b2f[943]:   File "/usr/local/lib/python3.5/dist-packages/zmon_aws_agent-0.2-py3.5.egg/zmon_aws_agent/aws.py", line 96, in populate_dns_data  
15:21:08.567 zmon-zmon /var/log/application.log  Aug  2 13:21:05 ip-172-31-142-36 docker/4be9b9f37b2f[943]:   File "/usr/local/lib/python3.5/dist-packages/zmon_aws_agent-0.2-py3.5.egg/zmon_aws_agent/aws.py", line 98, in <listcomp>  
15:21:08.567 zmon-zmon /var/log/application.log  Aug  2 13:21:05 ip-172-31-142-36 docker/4be9b9f37b2f[943]: KeyError: 'type'
