### ISSUE TITLE
Adding EC2 instance entity with upcoming events fails due to JSON+datetime serialization

### ISSUE THREAD

**Issue by a1exsh** [zalando-zmon/zmon-aws-agent#91]
Example log with stack trace:
```
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]: INFO:zmon-aws-agent:Adding new instance entity with ID: xxx-test-cd95-xyz[aws:NNN:eu-central-1]  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]: ERROR:zmon_cli.client:ZMON client failed in: add_entity  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]: ERROR:zmon-aws-agent:Failed to add entity: {'instance_type': 'm4.large', 'events': [{'Code': 'instance-stop', 'Description': 'The instance is running on degraded hardware', 'NotBefore': datetime.datetime(2017, 3, 17, 13, 0, tzinfo=tzlocal())}], 'state_reason': '', 'name': 'xxx-test', 'application_version': 'cd95', 'id': 'xxx-test-cd95-xyz[aws:NNN:eu-central-1]', 'runtime': 'Docker', 'ports': {'9042': '9042', '7001': '7001'}, 'aws_id': 'i-12345', 'created_by': 'agent', 'region': 'eu-central-1', 'block_devices': {'/dev/xvdf': {'attach_time': '2017-02-22 10:33:53+00:00', 'volume_type': 'ebs', 'volume_id': 'vol-54321'}, '/dev/sda1': {'attach_time': '2017-02-22 10:33:17+00:00', 'volume_type': 'ebs', 'volume_id': 'vol-09876'}}, 'host': '172.31.xx.yy', 'type': 'instance', 'spot_instance': False, 'application_id': 'xxx-test', 'ip': '172.31.xx.yy', 'source_base': 'registry.opensource.zalan.do/stups/planb-cassandra-2', 'source': 'registry.opensource.zalan.do/stups/planb-cassandra-2:cd-67', 'infrastructure_account': 'aws:NNN'}  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]: Traceback (most recent call last):  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/local/lib/python3.5/dist-packages/zmon_aws_agent-0.2-py3.5.egg/zmon_aws_agent/main.py", line 74, in add_new_entities  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     zmon_client.add_entity(entity)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/local/lib/python3.5/dist-packages/zmon_cli-1.1.46-py3.5.egg/zmon_cli/client.py", line 68, in wrapper  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     return f(*args, **kwargs)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/local/lib/python3.5/dist-packages/zmon_cli-1.1.46-py3.5.egg/zmon_cli/client.py", line 330, in add_entity  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     resp = self.session.put(self.endpoint(ENTITIES, trailing_slash=False), json=entity)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in put  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     return self.request('PUT', url, data=data, **kwargs)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 461, in request  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     prep = self.prepare_request(req)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 394, in prepare_request  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     hooks=merge_hooks(request.hooks, self.hooks),  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 297, in prepare  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     self.prepare_body(data, files, json)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 428, in prepare_body  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     body = complexjson.dumps(json)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     return _default_encoder.encode(obj)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/lib/python3.5/json/encoder.py", line 198, in encode  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     chunks = self.iterencode(o, _one_shot=True)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     return _iterencode(o, 0)  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:   File "/usr/lib/python3.5/json/encoder.py", line 179, in default  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]:     raise TypeError(repr(o) + " is not JSON serializable")  
Mar  6 15:24:39 ip-aa-bb-cc-dd docker/5ec84e28e5b3[810]: TypeError: datetime.datetime(2017, 3, 17, 13, 0, tzinfo=tzlocal()) is not JSON serializable  
```

**Comment by mohabusama** [comment]
https://github.com/zalando-zmon/zmon-cli/issues/46
